blog/urls.py
from django.conf.urls import patterns, url
from views import index, ArticleView, ArticlePublish, not_found, Contact, about, Test, RegisterView, cus_login, cus_logout, page_not_found, search

urlpatterns = patterns('',
                       url(r'^$', index, name='index'),
                       url(r'^article/$', ArticleView.as_view(), name='article_detail'),
                       url(r'^articlepublish/$', ArticlePublish.as_view(), name='article_publish'),
                       url(r'^404/$', not_found),
                       url(r'^contact/$', Contact.as_view(), name='contact'),
                       url(r'^about/$', about, name='about'),
                       url(r'^test/$', Test.as_view()),
                       url(r'^register/$', RegisterView.as_view(), name='register'),
                       url(r'^login/$', cus_login, name='login'),
                       url(r'^logout/$', cus_logout, name='logout'),
                       url(r'^search/$', search, name='search'),
                       url(r'^.*/$', page_not_found, name='not_found'),
        )

myblog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myblog.views.home', name='home'),
    url(r'^blog/', include('blog.urls')),
    url(r'^uploads/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^admin/', include(admin.site.urls)),
    )

handler404 = 'blog.views.page_not_found'

blog/models.py
#-*- coding:utf-8 -*-
from django.db import models
from django.contrib.auth.models import User, AbstractUser

# Create your models here.

class UserProfile(AbstractUser):
    avatar = models.ImageField(upload_to='avatar/%Y/%m', default='avatar/default.png', max_length=200, blank=True, null=True, verbose_name='头像')
    description = models.CharField("个人简介", blank=True, null=True, max_length=200)
    qq = models.CharField(max_length=20, blank=True, null=True, verbose_name='QQ号码')
    phone_num = models.CharField(max_length=11, blank=True, null=True, verbose_name='手机号码')

    class Meta:
        verbose_name = "用户"
        verbose_name_plural = "用户"
        ordering = ['-id']

    def __unicode__(self):
        return self.username


class Tag(models.Model):
    name = models.CharField("标签", max_length=20)
    create_time = models.DateTimeField("创建时间", auto_now_add=True)

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = "标签"
        ordering = ['name']

    def __unicode__(self):
        return self.name

class Catagory(models.Model):
    name = models.CharField("分类", max_length=30)
    create_time = models.DateTimeField("创建时间", auto_now_add=True)

    class Meta:
        verbose_name = "分类"
        verbose_name_plural = "分类"
        ordering = ['name']

    def __unicode__(self):
        return self.name


class Article(models.Model):
    title = models.CharField("标题", max_length=50)
    author = models.ForeignKey(UserProfile, verbose_name="作者")
    content = models.TextField("文章内容")
    img = models.ImageField("文章题图", upload_to='article/%Y/%m', blank=True, null=True, max_length=1024*5)
    tags = models.ManyToManyField(Tag, "标签")
    catagory = models.ForeignKey(Catagory, verbose_name="分类")
    publish_time = models.DateTimeField("发表时间", auto_now_add=True)
    praise_count = models.IntegerField("点赞", default=0)


    class Meta:
        verbose_name = "文章"
        verbose_name_plural = "文章"
        ordering = ['publish_time']

    def __unicode__(self):
        return self.title


class Comment(models.Model):
    user = models.IntegerField("用户ID", blank=True)  #save the user's id if login, and let the visitor comment
    username = models.CharField("称呼", max_length=30)
    useremail = models.EmailField("邮箱")
    content = models.CharField("评论内容", max_length=200)
    article = models.ForeignKey(Article, verbose_name="文章")
    create_time = models.DateTimeField("评论时间", auto_now_add=True)

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = "评论"
        ordering = ['create_time']

    def __unicode__(self):
        return str(self.id)


class Message(models.Model):
    name = models.CharField("称呼", max_length=50)
    email = models.EmailField("邮箱")
    message = models.TextField("留言")
    create_time = models.DateTimeField("留言时间", auto_now_add=True)

    class Meta:
        verbose_name = "留言"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return str(self.id)

templates/About.html
{% extends 'base.html' %}


{% block custom_css %}
{% endblock %}


{% block title %}
    About
{% endblock %}


{% block menu %}
    <ul id="menu-primary-items" class="menu-primary-items">
        <li id="menu-item-111" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-111"><a href="/blog/">Home</a></li>
        <li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113  current-menu-item"><a href="/blog/about/">About</a></li>
        <li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113"><a href="/blog/contact/">Contact me</a></li>
    </ul>
{% endblock %}


{% block main %}
    <section id="main" class="main" role="main">
        <div class="entry page publish author-drop-live-demo post-61">
		    <article>
				<div class="post-container">
			        <div class="post-header">
				        <h2 class="post-title">About</h2>
			        </div>
			        <div class="post-content">
				        <p>Apex is a sophisticated, minimalist theme.</p>
                        <p>It looks great and performs wonderfully on phones, tablets, laptops, and everything in between.</p>
                        <p>As a fast, responsive, accessibility-ready, and translation-ready theme, Apex is a theme you can trust to present your content to the world.</p>
                    </div>
		        </div>
			</article>
    	</div>
    </section> <!-- .main -->
{% endblock %}




{% block custom_js %}
{% endblock %}

templates/ArticlePublish.html
{% extends 'base.html' %}


{% block custom_css %}
{% endblock %}


{% block title %}
    ArticlePublis
{% endblock %}


{% block menu %}
    <ul id="menu-primary-items" class="menu-primary-items">
        <li id="menu-item-111" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-111"><a href="/blog/">Home</a></li>
        <li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113"><a href="/blog/about/">About</a></li>
        <li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113"><a href="/blog/contact/">Contact me</a></li>
    </ul>
{% endblock %}


{% block main %}
    <section id="main" class="main" role="main">
        <div class="entry post publish author-drop-live-demo post-44 format-standard has-post-thumbnail sticky category-cooking category-news post_tag-blogging post_tag-funny post_tag-new">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p>Title*: {{ form.title }}</p>
                <p>Img: <input type="file" name="img"></p>
                <p> Content*: </p>
                {{ form.content }}
                <p>Catagory*:
                    <select name="catagory">
                        {% for catagory in catagorys %}
                            <option value="{{ catagory.id }}">{{ catagory.name }}</option>
                        {% endfor %}
                    </select>
                </p>
                <p>Tag*:
                    <select multiple="multiple" id="id_tags" name="tags">
                        {% for tag in tags %}
                            <option value="{{ tag.id }}">{{ tag.name }}</option>
                        {% endfor %}
                    </select>
                </p>
                <input type="submit" value="Publish">
            </form>
        </div>
    </section>
{% endblock %}


{% block custom_js %}
    <script src="/static/js/tinymce/tinymce.min.js"></script>
    <script src="/static/js/tinymce/config.js"></script>
{% endblock %}

templates/Contact.html
{% extends 'base.html' %}


{% block custom_css %}
{% endblock %}


{% block title %}
    Contact
{% endblock %}


{% block menu %}
    <ul id="menu-primary-items" class="menu-primary-items">
        <li id="menu-item-111" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-111"><a href="/blog/">Home</a></li>
        <li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113"><a href="/blog/about/">About</a></li>
        <li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113 current-menu-item"><a href="/blog/contact/">Contact me</a></li>
    </ul>
{% endblock %}


{% block main %}
    <section id="main" class="main" role="main">
        <div class="entry page publish author-drop-live-demo post-68">
		    <article>
				<div class="post-container">
                    <div class="post-header">
                        <h2 class="post-title">Contact</h2>
                    </div>
		        	<div class="post-content">
                        <div id="simple-contact-form" class="scf">
                            <form action="" method="post">
                                {% csrf_token %}
                                <fieldset class="scf-name">
                                    <label for="scf_name">Name (Required)</label>
                                    <input name="name" id="scf_name" type="text" size="33" maxlength="99" value="" placeholder="Your Name">
                                </fieldset>
                                <fieldset class="scf-email">
                                    <label for="scf_email">Email (Required)</label>
                                    <input name="email" id="scf_email" type="text" size="33" maxlength="99" value="" placeholder="Your Email">
                                </fieldset>
                                <fieldset class="scf-message">
                                    <label for="scf_message">Message (Required)</label>
                                    <textarea name="message" id="scf_message" cols="33" rows="7" placeholder="Your Message"></textarea>
                                </fieldset>
                                <div class="scf-submit">
                                    <input type="submit" name="Submit" id="scf_contact" value="Send email">
                                </div>
                            </form>
                        </div>
                        <style>#simple-contact-form fieldset { width: 100%; overflow: hidden; margin: 12px 0; border: 0; padding: 1px; } #simple-contact-form fieldset input { float: left; width: 60%; } #simple-contact-form textarea { float: left; clear: both; width: 95%; } #simple-contact-form label { float: none; clear: both; display: block; margin-bottom: 12px;}</style><div style="clear:both">&nbsp;</div>
                    </div>
                </div>
            </article>
	    </div>
    </section> <!-- .main -->
{% endblock %}


{% block custom_js %}
{% endblock %}

templates/Detail.html
{% extends 'base.html' %}


{% block title %}
    {{ article.title }}
{% endblock %}


{% block custom_css%}
{% endblock %}


{% block menu %}
    <ul id="menu-primary-items" class="menu-primary-items">
        <li id="menu-item-111" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-111"><a href="/blog/">Home</a></li>
        <li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113"><a href="/blog/about/">About</a></li>
        <li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113"><a href="/blog/contact/">Contact me</a></li>
    </ul>
{% endblock %}


{% block main %}
    <section id="main" class="main" role="main">
        <div class="entry post publish author-drop-live-demo post-19 format-standard has-post-thumbnail category-fashion category-gaming post_tag-blogging post_tag-cooking post_tag-fashion post_tag-food">
		    <article>
                <div class="featured-image" style="background-image: url(/uploads/{{ article.img }}">
{#                    <img src="/uploads/{{ article.img }}">#}
                </div>
                <div class="post-container">
                    <div class="post-header">
                        <h2 class="post-title">{{ article.title }}</h2>
                        <span class="post-date">
                            Published {{ article.publish_time | date:"F d, Y" }}				</span>
                    </div>
                    <div class="post-content">
                        {{ article.content | safe }}
                    </div>
                    <div class="post-meta">
                        <p class="post-categories">
                            <span>Published in </span>
                            <a href="https://www.competethemes.com/apex-live-demo/category/fashion/" title="View all posts in fashion">{{ article.catagory }}</a>
                        </p>
                        <div class="post-tags">
                            <ul>
                                {% for tag in article.tags.all %}
                                    <li>
                                        <a href="#" title="View all posts tagged blogging">{{ tag.name }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% if next_post or previous_post %}
                        <nav class="further-reading">
                            <div class="previous">
                                {% if previous_post %}
                                    <span>Previous Post</span>
                                    <a href="/blog/article/?id={{ previous_post.id }}">{{ previous_post.title }}</a>
                                {% endif %}
                            </div>
                            <div class="next">
                                {% if next_post %}
                                    <span>Previous Post</span>
                                    <a href="/blog/article/?id={{ next_post.id }}">{{ next_post.title }}</a>
                                {% endif %}
                            </div>
                        </nav>
                    {% endif %}
                    </div>
                </div>
            </article>

            <section id="comments" class="comments">
                <div class="comments-number">
                    {% if not article.comment_set.all %}
                        <h3>Be First to Comment</h3>
                        </div>
                    {% else %}
                        <h3>Comments</h3>
                        </div>
                        {% for comment in article.comment_set.all %}
                            <ol class="comment-list">
                                <lable>{{ comment.username }}: </lable><lable>{{ comment.content }}</lable>
                            </ol>
                        {% endfor %}
                        <!-- .comment-list -->
                    {% endif %}

                <div id="respond" class="comment-respond">
                    <h3 id="reply-title" class="comment-reply-title">Leave a Reply</h3>
                    <form action="/blog/article/?id={{ article.id }}" method="post" id="commentform" class="comment-form" novalidate="">
                        {% csrf_token %}
                        {% if not user.is_authenticated %}
                            <p class="comment-notes">
                                <span id="email-notes">Your email address will not be published.</span> Required fields are marked <span class="required">*</span>
                            </p>
                            <p class="comment-form-author">
                                <label>Name*</label>
                                <input id="author" name="username" type="text" value="" size="30" aria-required="true">
                            </p>
                            <p class="comment-form-email">
                                <label>Email*</label>
                                <input id="email" name="email" type="email" value="" size="30" aria-required="true">
                            </p>
                        {% endif %}
                        <p class="comment-form-comment">
                            <label>Comment</label>
                            <textarea required="" id="comment" name="content" cols="45" rows="8" aria-required="true" min_length="10" placeholder="no more than 200 words"></textarea>
                        </p>
                        <p class="form-submit"><input name="submit" type="submit" id="submit" class="submit" value="Post Comment">
                        </p>
                    </form>
                </div>
                <!-- #respond -->
            </section>
            <!-- #comments -->
        </div>

    </section>
    <!-- .main -->

{% endblock %}

{% block custom_js %}
{% endblock %}

templates/Index.html
{% extends 'base.html' %}


{% block custom_css %}
{% endblock %}


{% block title %}
    Apex Live Demo: Sophisticated and minimalist
{% endblock %}


{% block menu %}
    <ul id="menu-primary-items" class="menu-primary-items">
        <li id="menu-item-111" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-111 current-menu-item"><a href="/blog/">Home</a></li>
        <li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113"><a href="/blog/about/">About</a></li>
        <li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113"><a href="/blog/contact/">Contact me</a></li>
    </ul>
{% endblock %}


{% block main %}
    <section id="main" class="main" role="main">
        <div class="entry post publish author-drop-live-demo post-44 format-standard has-post-thumbnail sticky category-cooking category-news post_tag-blogging post_tag-funny post_tag-new">
            {% for article in articles %}
                <article>
                    <div class="featured-image" style="background-image: url(/uploads/{{ article.img }})">
                        <a href="/blog/article/?id={{ article.id }}">{{ article.title }}</a>
                    </div>
                    <div class="post-container">
                        <div class="post-header">
                            <div class="sticky-status">
                                <span>Featured Post</span>
                            </div>
                            <h2 class="post-title">
                                <a href="/blog/article/?id={{ article.id }}">{{ article.title }}</a>
                            </h2>
                            <span class="post-date">Published {{ article.publish_time | date:"F d, Y" }}	</span>
                        </div>
                        <div class="post-content">
                            <p>{{ article.content | slice:":300" | safe}}...</p>
                            <p>
                                <a class="more-link" href="/blog/article/?id={{ article.id }}">Continue reading <span class="screen-reader-text">{{ article.title }}</span>
                                </a>
                            </p>
                            <span class="comments-link">
                                <i class="fa fa-comment" title="comment icon"></i>
                                <a href="/blog/article/?id={{ article.id }}">{{ article.set_comment | length }} Comments</a>
                            </span>
                        </div>
                    </div>
                </article>
            {% endfor %}
        </div>



        <!--分页-->
        <nav class="pagination loop-pagination"><span class="page-numbers current">1</span>
            <a class="page-numbers" href="https://www.competethemes.com/apex-live-demo/page/2/">2</a>
            <a class="next page-numbers" href="https://www.competethemes.com/apex-live-demo/page/2/">Next »</a>
        </nav>
    </section>
{% endblock %}


{% block custom_js %}
    <script type="text/javascript" src="/static/js/production.min.js"></script>
{% endblock %}

templates/Register.html
{% extends 'base.html' %}


{% block custom_css %}
{% endblock %}


{% block title %}
    Register
{% endblock %}


{% block menu %}
    <ul id="menu-primary-items" class="menu-primary-items">
        <li id="menu-item-111" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-111"><a href="/blog/">Home</a></li>
        <li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113"><a href="/blog/about/">About</a></li>
        <li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113"><a href="/blog/contact/">Contact me</a></li>
    </ul>
{% endblock %}


{% block main %}
    <section id="main" class="main" role="main">
        <div class="entry post publish author-drop-live-demo post-44 format-standard has-post-thumbnail sticky category-cooking category-news post_tag-blogging post_tag-funny post_tag-new">
            <div style="height: 100px">
                <h3 align="center">用户注册</h3>
            </div>
            <div id="simple-contact-form" class="scf">
                <form id="register" action="" method="post">
                    {% csrf_token %}
                    <p>昵称*</p>
                    {{ form.username }}

                    <p>姓</p>
                    {{ form.last_name }}

                    <p>名</p>
                    {{ form.first_name }}

                    <p>密码*</p>
                    {{ form.password }}

                    <p>请再次输入密码*</p>
                    <input id="id_password1" type="password" maxlength="50" minlength="8">
                    <span id="psd_error" style="display: none;color: red">两次输入密码不一致！！！</span>

                    <p>邮箱*</p>
                    {{ form.email }}

                    <p>QQ</p>
                    {{ form.qq }}

                    <p>电话号码</p>
                    {{ form.phone_num }}
                    <br></br>
                    <button type="button" onclick="checkoutpwd()">注 册</button>
                </form>
            </div>

        </div>
    </section>
{% endblock %}


{% block custom_js %}
    <script type="text/javascript">
        function checkoutpwd(){
            var psd1 = $("#id_password").val();
            var psd2 = $("#id_password1").val();
            if (psd1==psd2){
                console.log('yes');
                $("#register").submit();
            }else{
                $("#psd_error").show();
            }

        }
    </script>
{% endblock %}

templates/Register_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册成功</title>
</head>
<body>
    <h3 align="center">注册成功，3秒后跳转至首页。。。。</h3>
    <script type="text/javascript">
        function tiaozhuan(){
            window.location.href = "/blog/";
        }
        window.setTimeout("tiaozhuan()", 3000);
    </script>
</body>
</html>

templates/Search_result.html
{% extends 'base.html' %}


{% block custom_css %}
{% endblock %}


{% block title %}
    Search Result
{% endblock %}


{% block menu %}
    <ul id="menu-primary-items" class="menu-primary-items">
        <li id="menu-item-111" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-111"><a href="/blog/">Home</a></li>
        <li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113"><a href="/blog/about/">About</a></li>
        <li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113"><a href="/blog/contact/">Contact me</a></li>
    </ul>
{% endblock %}


{% block main %}
    {% if keyword %}
        <h3 style="min-height: 30px"><em>Search '{{ keyword }}'</em></h3>
    {% elif catagory %}
        <h3 style="min-height: 30px"><em>Search '{{ catagory.name }}'</em></h3>
    {% elif tag %}
        <h3 style="min-height: 30px"><em>Search '{{ tag.name }}'</em></h3>
    {% endif %}
    <section id="main" class="main" role="main">
        <div class="entry post publish author-drop-live-demo post-44 format-standard has-post-thumbnail sticky category-cooking category-news post_tag-blogging post_tag-funny post_tag-new">
            {% for article in articles %}
                <article>
                    {% if article.img %}
                        <div class="featured-image" style="background-image: url(/uploads/{{ article.img }})">
                            <a href="/blog/article/?id={{ article.id }}">{{ article.title }}</a>
                        </div>
                    {% endif %}
                    <div class="post-container">
                        <div class="post-header">
{#                            <div class="sticky-status">#}
{#                                <span>Featured Post</span>#}
{#                            </div>#}
                            <h2 class="post-title">
                                <a href="/blog/article/?id={{ article.id }}">{{ article.title }}</a>
                            </h2>
                            <span class="post-date">Published {{ article.publish_time | date:"F d, Y" }}	</span>
                        </div>
                        <div class="post-content">
                            <p>{{ article.content | slice:":300" | safe}}...</p>
                            <p>
                                <a class="more-link" href="/blog/article/?id={{ article.id }}">Continue reading <span class="screen-reader-text">{{ article.title }}</span>
                                </a>
                            </p>
                            <span class="comments-link">
                                <i class="fa fa-comment" title="comment icon"></i>
                                <a href="/blog/article/?id={{ article.id }}">{{ article.comment_set.all | length }} Comments</a>
                            </span>
                        </div>
                    </div>
                </article>
            {% endfor %}
        </div>



        <!--分页-->
        <nav class="pagination loop-pagination">
            {% if articles.has_previous %}
                <a class="next page-numbers" href="?page={{ articles.previous_page_number }}">« Previous</a>
            {% endif %}
            {% for page in articles.paginator.page_range %}
                {% if page == cur_page %}
                    <span class="page-numbers current">{{ page }}</span>
                {% else %}
                    <a class="page-numbers" href="?page={{ page }}">{{ page }}</a>
                {% endif %}
            {% endfor %}
            {% if articles.has_next %}
                <a class="next page-numbers" href="?page={{ articles.next_page_number }}">Next »</a>
            {% endif %}
        </nav>
    </section>
{% endblock %}


{% block custom_js %}
    <script type="text/javascript" src="/static/js/production.min.js"></script>
{% endblock %}

templates/model.html
{% extends 'base.html' %}


{% block custom_css %}
{% endblock %}


{% block title %}
    Register
{% endblock %}


{% block menu %}
    <ul id="menu-primary-items" class="menu-primary-items">
        <li id="menu-item-111" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-111"><a href="/static/css/Apex Live Demo_ Sophisticated and minimalist.html">Home</a></li>
        <li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113"><a href="https://www.competethemes.com/apex-live-demo/about/">About</a></li>
        <li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113"><a href="https://www.competethemes.com/apex-live-demo/about/">Contact me</a></li>
    </ul>
{% endblock %}


{% block main %}
    <section id="main" class="main" role="main">
        <div class="entry post publish author-drop-live-demo post-44 format-standard has-post-thumbnail sticky category-cooking category-news post_tag-blogging post_tag-funny post_tag-new">

        </div>
    </section>
{% endblock %}


{% block custom_js %}
{% endblock %}

templates/register.html
{% extends 'base.html' %}


{% block custom_css %}
{% endblock %}


{% block title %}
    Register
{% endblock %}


{% block menu %}
    <ul id="menu-primary-items" class="menu-primary-items">
        <li id="menu-item-111" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-111"><a href="/blog/">Home</a></li>
        <li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113"><a href="/blog/about/">About</a></li>
        <li id="menu-item-113" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-113"><a href="/blog/contact/">Contact me</a></li>
    </ul>
{% endblock %}


{% block main %}
    <section id="main" class="main" role="main">
        <div class="entry post publish author-drop-live-demo post-44 format-standard has-post-thumbnail sticky category-cooking category-news post_tag-blogging post_tag-funny post_tag-new">
            <div style="height: 100px">
                <h3 align="center">用户注册</h3>
            </div>
            <div id="simple-contact-form" class="scf">
                <form id="register" action="" method="post">
                    {% csrf_token %}
                    <p>昵称*</p>
                    {{ form.username }}

                    <p>姓</p>
                    {{ form.last_name }}

                    <p>名</p>
                    {{ form.first_name }}

                    <p>密码*</p>
                    {{ form.password }}

                    <p>请再次输入密码*</p>
                    <input id="id_password1" type="password" maxlength="50" minlength="8">
                    <span id="psd_error" style="display: none;color: red">两次输入密码不一致！！！</span>

                    <p>邮箱*</p>
                    {{ form.email }}

                    <p>QQ</p>
                    {{ form.qq }}

                    <p>电话号码</p>
                    {{ form.phone_num }}
                    <br></br>
                    <button type="button" onclick="checkoutpwd()">注 册</button>
                </form>
            </div>

        </div>
    </section>
{% endblock %}


{% block custom_js %}
    <script type="text/javascript">
        function checkoutpwd(){
            var psd1 = $("#id_password").val();
            var psd2 = $("#id_password1").val();
            if (psd1==psd2){
                console.log('yes');
                $("#register").submit();
            }else{
                $("#psd_error").show();
            }

        }
    </script>
{% endblock %}

templates/register_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册成功</title>
</head>
<body>
    <h3 align="center">注册成功，3秒后跳转至首页。。。。</h3>
    <script type="text/javascript">
        function tiaozhuan(){
            window.location.href = "/blog/";
        }
        window.setTimeout("tiaozhuan()", 3000);
    </script>
</body>
</html>